package iptables_test

import (
	"net"
	"testing"

	. "github.com/onsi/gomega"

	"github.com/mazdakn/fwsim/convertors/iptables"
	"github.com/mazdakn/fwsim/pkg/proto"
	"github.com/mazdakn/fwsim/pkg/rule"
)

// parseIP is a test helper that parses an IP address string into a net.IP.
// IPv4 addresses are returned as 4-byte form; IPv6 as 16-byte form.
func parseIP(s string) net.IP {
	ip := net.ParseIP(s)
	if ip == nil {
		panic("invalid IP: " + s)
	}
	if v4 := ip.To4(); v4 != nil {
		return v4
	}
	return ip
}

// ── basic table / chain structure ────────────────────────────────────────────

func TestConvertEmptyInput(t *testing.T) {
	RegisterTestingT(t)
	tables, err := iptables.Convert("")
	Expect(err).To(BeNil())
	Expect(tables).To(BeEmpty())
}

func TestConvertSingleTableNoRules(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	Expect(tables).To(HaveLen(1))
	Expect(tables[0].Name).To(Equal("filter"))
	Expect(tables[0].Chains).To(HaveLen(3))
}

func TestConvertMultipleTables(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
COMMIT
*nat
:PREROUTING ACCEPT [0:0]
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	Expect(tables).To(HaveLen(2))
	Expect(tables[0].Name).To(Equal("filter"))
	Expect(tables[1].Name).To(Equal("nat"))
}

func TestConvertIgnoresComments(t *testing.T) {
	RegisterTestingT(t)
	input := `# Generated by iptables-save
*filter
# comment inside table
:INPUT ACCEPT [0:0]
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	Expect(tables).To(HaveLen(1))
}

// ── action mapping ────────────────────────────────────────────────────────────

func TestConvertAcceptAction(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -j ACCEPT
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	chain := tables[0].Chains["INPUT"]
	Expect(chain.Rules).To(HaveLen(1))
	Expect(chain.Rules[0].Action).To(Equal(rule.Accept))
}

func TestConvertDropAction(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -j DROP
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	Expect(tables[0].Chains["INPUT"].Rules[0].Action).To(Equal(rule.Drop))
}

func TestConvertRejectMappedToDrop(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -j REJECT
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	Expect(tables[0].Chains["INPUT"].Rules[0].Action).To(Equal(rule.Drop))
}

func TestConvertReturnAction(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -j RETURN
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	Expect(tables[0].Chains["INPUT"].Rules[0].Action).To(Equal(rule.Return))
}

func TestConvertUserChainJump(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
:MY-CHAIN - [0:0]
-A INPUT -j MY-CHAIN
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	r := tables[0].Chains["INPUT"].Rules[0]
	Expect(r.Action).To(Equal(rule.Jump))
	Expect(r.JumpTarget).To(Equal("MY-CHAIN"))
}

// ── protocol matching ─────────────────────────────────────────────────────────

func TestConvertProtocolTCP(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp -j ACCEPT
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	r := tables[0].Chains["INPUT"].Rules[0]
	Expect(r.Proto).ToNot(BeNil())
	Expect(r.Proto.Match(proto.TCP)).To(BeTrue())
	Expect(r.Proto.Match(proto.UDP)).To(BeFalse())
}

func TestConvertProtocolUDP(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -p udp -j ACCEPT
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	r := tables[0].Chains["INPUT"].Rules[0]
	Expect(r.Proto).ToNot(BeNil())
	Expect(r.Proto.Match(proto.UDP)).To(BeTrue())
}

func TestConvertNegatedProtocol(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT ! -p tcp -j ACCEPT
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	r := tables[0].Chains["INPUT"].Rules[0]
	Expect(r.NotProto).ToNot(BeNil())
	Expect(r.NotProto.Match(proto.TCP)).To(BeTrue())
	Expect(r.Proto).To(BeNil())
}

// ── source / destination addresses ───────────────────────────────────────────

func TestConvertSourceCIDR(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -s 10.0.0.0/8 -j ACCEPT
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	r := tables[0].Chains["INPUT"].Rules[0]
	Expect(r.Source.Net).ToNot(BeNil())
	Expect(r.Source.Net.Match(parseIP("10.1.2.3"))).To(BeTrue())
	Expect(r.Source.Net.Match(parseIP("192.168.1.1"))).To(BeFalse())
}

func TestConvertSourcePlainIP(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -s 192.168.1.1 -j ACCEPT
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	r := tables[0].Chains["INPUT"].Rules[0]
	Expect(r.Source.Net).ToNot(BeNil())
	Expect(r.Source.Net.Match(parseIP("192.168.1.1"))).To(BeTrue())
	Expect(r.Source.Net.Match(parseIP("192.168.1.2"))).To(BeFalse())
}

func TestConvertDestinationCIDR(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:OUTPUT ACCEPT [0:0]
-A OUTPUT -d 172.16.0.0/12 -j DROP
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	r := tables[0].Chains["OUTPUT"].Rules[0]
	Expect(r.Destination.Net).ToNot(BeNil())
	Expect(r.Destination.Net.Match(parseIP("172.16.5.1"))).To(BeTrue())
	Expect(r.Destination.Net.Match(parseIP("10.0.0.1"))).To(BeFalse())
}

func TestConvertNegatedSource(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT ! -s 10.0.0.0/8 -j DROP
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	r := tables[0].Chains["INPUT"].Rules[0]
	Expect(r.NotSource.Net).ToNot(BeNil())
	Expect(r.NotSource.Net.Match(parseIP("10.0.0.1"))).To(BeTrue())
	Expect(r.Source.Net).To(BeNil())
}

func TestConvertNegatedDestination(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:OUTPUT ACCEPT [0:0]
-A OUTPUT ! -d 10.0.0.0/8 -j DROP
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	r := tables[0].Chains["OUTPUT"].Rules[0]
	Expect(r.NotDestination.Net).ToNot(BeNil())
	Expect(r.Destination.Net).To(BeNil())
}

// ── port matching ─────────────────────────────────────────────────────────────

func TestConvertDstPort(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp --dport 80 -j ACCEPT
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	r := tables[0].Chains["INPUT"].Rules[0]
	Expect(r.Destination.Port).ToNot(BeNil())
	Expect(r.Destination.Port.Match(uint16(80))).To(BeTrue())
	Expect(r.Destination.Port.Match(uint16(443))).To(BeFalse())
}

func TestConvertSrcPort(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp --sport 1024 -j ACCEPT
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	r := tables[0].Chains["INPUT"].Rules[0]
	Expect(r.Source.Port).ToNot(BeNil())
	Expect(r.Source.Port.Match(uint16(1024))).To(BeTrue())
	Expect(r.Source.Port.Match(uint16(80))).To(BeFalse())
}

func TestConvertPortRange(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp --dport 1024:65535 -j ACCEPT
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	r := tables[0].Chains["INPUT"].Rules[0]
	Expect(r.Destination.Port).ToNot(BeNil())
	Expect(r.Destination.Port.Match(uint16(1024))).To(BeTrue())
	Expect(r.Destination.Port.Match(uint16(8080))).To(BeTrue())
	Expect(r.Destination.Port.Match(uint16(443))).To(BeFalse())
}

func TestConvertNegatedDstPort(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp ! --dport 22 -j ACCEPT
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	r := tables[0].Chains["INPUT"].Rules[0]
	Expect(r.NotDestination.Port).ToNot(BeNil())
	Expect(r.NotDestination.Port.Match(uint16(22))).To(BeTrue())
	Expect(r.Destination.Port).To(BeNil())
}

func TestConvertMultiportDports(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp -m multiport --dports 80,443,8080 -j ACCEPT
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	r := tables[0].Chains["INPUT"].Rules[0]
	Expect(r.Destination.Port).ToNot(BeNil())
	Expect(r.Destination.Port.Match(uint16(80))).To(BeTrue())
	Expect(r.Destination.Port.Match(uint16(443))).To(BeTrue())
	Expect(r.Destination.Port.Match(uint16(8080))).To(BeTrue())
	Expect(r.Destination.Port.Match(uint16(22))).To(BeFalse())
}

func TestConvertMultiportSports(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp -m multiport --sports 1024:2048,9000 -j ACCEPT
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	r := tables[0].Chains["INPUT"].Rules[0]
	Expect(r.Source.Port).ToNot(BeNil())
	Expect(r.Source.Port.Match(uint16(1024))).To(BeTrue())
	Expect(r.Source.Port.Match(uint16(2048))).To(BeTrue())
	Expect(r.Source.Port.Match(uint16(9000))).To(BeTrue())
	Expect(r.Source.Port.Match(uint16(80))).To(BeFalse())
}

// ── interface matching ────────────────────────────────────────────────────────

func TestConvertIngressInterface(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -i eth0 -j ACCEPT
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	r := tables[0].Chains["INPUT"].Rules[0]
	Expect(r.Source.Iface).ToNot(BeNil())
	Expect(r.Source.Iface.Match("eth0")).To(BeTrue())
	Expect(r.Source.Iface.Match("eth1")).To(BeFalse())
}

func TestConvertEgressInterface(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:OUTPUT ACCEPT [0:0]
-A OUTPUT -o eth1 -j ACCEPT
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	r := tables[0].Chains["OUTPUT"].Rules[0]
	Expect(r.Destination.Iface).ToNot(BeNil())
	Expect(r.Destination.Iface.Match("eth1")).To(BeTrue())
}

func TestConvertNegatedIngressInterface(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT ! -i lo -j ACCEPT
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	r := tables[0].Chains["INPUT"].Rules[0]
	Expect(r.NotSource.Iface).ToNot(BeNil())
	Expect(r.NotSource.Iface.Match("lo")).To(BeTrue())
	Expect(r.Source.Iface).To(BeNil())
}

// ── combined / real-world rules ───────────────────────────────────────────────

func TestConvertComplexRule(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -s 10.0.0.0/8 -p tcp --dport 443 -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -j DROP
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	Expect(tables).To(HaveLen(1))
	chain := tables[0].Chains["INPUT"]
	Expect(chain.Rules).To(HaveLen(3))

	r0 := chain.Rules[0]
	Expect(r0.Source.Net.Match(parseIP("10.1.1.1"))).To(BeTrue())
	Expect(r0.Proto.Match(proto.TCP)).To(BeTrue())
	Expect(r0.Destination.Port.Match(uint16(443))).To(BeTrue())
	Expect(r0.Action).To(Equal(rule.Accept))

	r1 := chain.Rules[1]
	Expect(r1.Source.Iface.Match("lo")).To(BeTrue())
	Expect(r1.Action).To(Equal(rule.Accept))

	r2 := chain.Rules[2]
	Expect(r2.Action).To(Equal(rule.Drop))
}

func TestConvertRuleOrdering(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp --dport 22 -j ACCEPT
-A INPUT -p tcp --dport 80 -j ACCEPT
-A INPUT -j DROP
COMMIT
`
	tables, err := iptables.Convert(input)
	Expect(err).To(BeNil())
	chain := tables[0].Chains["INPUT"]
	Expect(chain.Rules).To(HaveLen(3))
	Expect(chain.Rules[0].Destination.Port.Match(uint16(22))).To(BeTrue())
	Expect(chain.Rules[1].Destination.Port.Match(uint16(80))).To(BeTrue())
	Expect(chain.Rules[2].Action).To(Equal(rule.Drop))
}

// ── error handling ────────────────────────────────────────────────────────────

func TestConvertRuleBeforeTable(t *testing.T) {
	RegisterTestingT(t)
	_, err := iptables.Convert("-A INPUT -j ACCEPT\n")
	Expect(err).ToNot(BeNil())
	Expect(err.Error()).To(ContainSubstring("before table declaration"))
}

func TestConvertChainPolicyBeforeTable(t *testing.T) {
	RegisterTestingT(t)
	_, err := iptables.Convert(":INPUT ACCEPT [0:0]\n")
	Expect(err).ToNot(BeNil())
	Expect(err.Error()).To(ContainSubstring("before table declaration"))
}

func TestConvertInvalidProtocol(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -p notaproto -j ACCEPT
COMMIT
`
	_, err := iptables.Convert(input)
	Expect(err).ToNot(BeNil())
	Expect(err.Error()).To(ContainSubstring("protocol"))
}

func TestConvertInvalidSourceIP(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -s notanip -j ACCEPT
COMMIT
`
	_, err := iptables.Convert(input)
	Expect(err).ToNot(BeNil())
	Expect(err.Error()).To(ContainSubstring("source address"))
}

func TestConvertMissingFlagValue(t *testing.T) {
	RegisterTestingT(t)
	input := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -p
COMMIT
`
	_, err := iptables.Convert(input)
	Expect(err).ToNot(BeNil())
}
